name: $(Build.SourceVersion)
jobs:
  - template: .ci/build-test-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-16.04
      STAGING_DIRECTORY: /home/vsts/STAGING
      STAGING_DIRECTORY_UNIX: /home/vsts/STAGING
      ESY__CACHE_INSTALL_PATH: /home/vsts/.esy/3_____________________________________________________________________/i
      ESY__CACHE_SOURCE_TARBALL_PATH: /home/vsts/.esy/source/i

  - template: .ci/build-test-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-10.13
      STAGING_DIRECTORY: /Users/vsts/STAGING
      STAGING_DIRECTORY_UNIX: /Users/vsts/STAGING
      ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i
      ESY__CACHE_SOURCE_TARBALL_PATH: /Users/vsts/.esy/source/i
