parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"
  STAGING_DIRECTORY: /Users/vsts/STAGING
  STAGING_DIRECTORY_UNIX: /Users/vsts/STAGING
  ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i
  ESY__CACHE_SOURCE_TARBALL_PATH: /Users/vsts/.esy/source/i

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      STAGING_DIRECTORY: ${{ parameters.STAGING_DIRECTORY }}
      STAGING_DIRECTORY_UNIX: ${{ parameters.STAGING_DIRECTORY_UNIX }}
      ESY__CACHE_INSTALL_PATH: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      ESY__CACHE_SOURCE_TARBALL_PATH: ${{ parameters.ESY__CACHE_SOURCE_TARBALL_PATH }}

    steps:
      - template: use-node.yml
      - template: restore-build-cache.yml
      - template: esy-build-steps.yml
      - ${{ if ne(parameters.platform, 'Windows') }}:
          - template: build-test.yml
            parameters:
              OCAML_VERSION: "4.04"
      - template: build-test.yml
        parameters:
          OCAML_VERSION: "4.06"
      - template: build-test.yml
        parameters:
          OCAML_VERSION: "4.07"
      - template: publish-build-cache.yml
