name: Validate Pull Request

on: [push, pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ${{ matrix.os }}
    strategy:
      # If we have many bug we can test on all plateform
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml_version: [4.04, 4.06, 4.07, 4.08]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v1
      - name: Install esy
        run: npm install -g esy@0.5.8
      - name: Try to restore dependencies cache
        id: deps-cache
        uses: actions/cache@v1
        with:
          path: ${{ runner.home }}/.esy
          key: ${{ matrix.os }}-${{ matrix.ocaml_version }}-${{ hashFiles('package-ci-*.*.esy.lock/index.json') }}
      - name: Install dependencies
        run: esy install -P package-ci-${{ matrix.ocaml_version }}
      - name: Build dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: esy build-dependencies -P package-ci-${{ matrix.ocaml_version }}
      - name: Build
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: esy build -P package-ci-${{ matrix.ocaml_version }}
      - name: Test
        if: matrix.os != 'windows-latest'
        run: |
          esy add -P package-ci-${{ matrix.ocaml_version }} "@opam/patience_diff"
          esy -P package-ci-${{ matrix.ocaml_version }} -- dune runtest --no-buffer --force
