name: Validate Pull Request

on: [pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml_version: [4.04, 4.06, 4.07, 4.08]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v1
      - name: Install esy
        run: npm install -g esy@0.5.8
      - name: Install dependencies
        run: esy install -P package-ci-${{ matrix.ocaml_version }}
      - name: Build
        run: esy build -P package-ci-${{ matrix.ocaml_version }}
      - name: Test
        run: esy -P package-ci-${{ matrix.ocaml_version }} -- dune runtest --no-buffer --force
